### ISSUE TITLE
Logging Out while in hyberbox reset's player location

### ISSUE THREAD

**Issue by Caltinor** [Commoble/hyperbox#10]
**Observation**
When logging out of a singleplayer world while inside a hyperbox, the player will be placed in the overworld upon relog.

**Expectation**
Either to log back in and still be inside the hyperbox or be outside the box but beside/near it.

**Steps to Repoduce**
1. travel to a random location
2. place and enter a hyberbox
3. save and exit world
4. load world
5. find yourself at worldspawn

__Versions:__
Forge: 43.1.58
Hyperbox: 1.19-3.0.0.0

**Details that might be relevant**
1. I do not have a home bed location
2. My hyperbox was underground when i logged out, and the Y coordinate when i logged back in seemed to be similar (my XZ was worldspawn but my Y seemed to mimic the Y of my hyperbox.

there appears to be a saved data error in the log as well.
[latest.log](https://github.com/Commoble/hyperbox/files/10142340/latest.log)
The hyperbox is named "1337" because I couldn't think of a name that did not use the letter "e".  I planned to make an issue about not being able to use the letter in in the box name (because it closes the gui) too.

**Comment by Commoble** [comment]
Fixed in 3.0.1.0 (also fixed the inventory-keybind-gui problem)
