### ISSUE TITLE
Cables

### ISSUE THREAD

**Issue by Dinocraft1515YT** [Commoble/hyperbox#12]
Why not to make Hyperbox compatible with cables and pipes?
I really want that answer

**Comment by Commoble** [comment]
Hyperbox is compatible with cables and pipes if they use forge capabilities:

![image](https://github.com/Commoble/hyperbox/assets/12983805/cf2ca4f1-d2ce-4ef4-8aa6-28eda6b1497b)

For mods that don't, you can use hoppers or similar blocks to bridge the gap

**Comment by Dinocraft1515YT** [comment]
Try with pipez, tom's simple storage and refined storage

**Comment by Dinocraft1515YT** [comment]
Even, what is forge capabilities?
