### ISSUE TITLE
Hyberbox not saving and loading correctly 

### ISSUE THREAD

**Issue by NateKDavis** [Commoble/hyperbox#13]
In minecraft 1.20.1 with forge 47.2.0 if I place a box, enter it, place blocks, leave the box, break and pick it up and replace it in a different location, enter the box. It will not have saved any block placement. It does seem to save it if I disconnect from the server or close the single player game before moving the box. Items on the ground do not seem to be affect and the inventory isn't set back either. Could this get a fix please? Thank you for your time.

**Comment by twothe** [comment]
Having the same issue. This renders the entire mod unusable as it is right now.
