### ISSUE TITLE
Hyperbox don't save changes

### ISSUE THREAD

**Issue by sh3rfy** [Commoble/hyperbox#14]
Hyperbox reverses the destroyed blocks inside after destroying and then placing the hyperbox again

hyperbox-1.19.2-3.0.1.0.jar

MC version: 1.19.2
Forge: 43.3.2

To reproduce the bug:
-Place the box on the ground
-Click to enter it
-build something
-leave box
-enter again
-destroy what you built
-exit box
-destroy box
-set it up again
-enter the box
-now you will see the blocks you destroyed and collected earlier

**Comment by Commoble** [comment]
Hello, this was fixed in 1.20.1-4.0.0.1
