### ISSUE TITLE
Excessive mob sounds

### ISSUE THREAD

**Issue by decryptedchaos** [Commoble/hyperbox#15]
There may not be anything you can do a bout this I'm not sure.

You should be able to set a dimension not to spawn any mobs though i think..
  
I thought that was the case when i tried using dreadful dirt to create a mob farm inside, and it refused to spawn any mobs..  
 - could be hard coded into dreadful dirt I'm not sure
 
But after repurposing the cubes for storage and other things..  I've noticed that mob sounds are a problem  it sounds like hundreds of mobs are outside of the cube.  Which for me personally kind of makes the cubes a bit annoying to work with..

**Comment by Commoble** [comment]
ARE hundreds of mobs outside the cube?

**Comment by decryptedchaos** [comment]
>ARE hundreds of mobs outside the cube?



I can't confirm or deny.   The FTB map doesn't generate anything for the dimension it's just blank (as best i can tell) 
I tried warping through the wall which made me instantly and uncontrollably fall to my death at which point i was thoroughly annoyed (void)  and even with creative mode, /god and flight on   it still forces me down and i die

So i can't figure out how to test that. 

![image](https://github.com/Commoble/hyperbox/assets/1302391/e062dade-13dc-439e-b6cb-700c3448e07e)

**Comment by Commoble** [comment]
Right, the hyperbox dimension is void on the other side of the wall, I mean are there hundreds of mobs out in the "parent" dimension where you placed the box

**Comment by decryptedchaos** [comment]
I wasn't going to play today, but this got me wondering..  

I went back and checked,  the box is placed above my mob farm..  now i didn't think anything of this because the sounds are muffled in the overworld.  

Turning the farm off stopped the sounds inside the box.  go figure.

**Comment by Commoble** [comment]
They shouldn't be playing louder in the box than they are outside, so I'll investigate further

**Comment by Commoble** [comment]
Mob sounds are working as intended
