### ISSUE TITLE
Compatibility or Biome issue?

### ISSUE THREAD

**Issue by Rithenar** [Commoble/hyperbox#19]
I was trying to make a mob farm inside a Hyperbox with some dreadful dirt from Mob Grinding Utils. After placing the dirt you can see the particle effects but nothing will spawn. I moved the hyperbox to a different biome with the same effects. Spawners will work just fine.  EDIT: I tested with delightful dirt as well and with a patch of grass.

**Comment by Commoble** [comment]
Intended, the hyperbox biome doesn't have any mob spawns in it
