### ISSUE TITLE
AE + Fluxnet crashes Server

### ISSUE THREAD

**Issue by Satherov** [Commoble/hyperbox#26]
Doing the following steps leads to a Server crash in 1.20
- place a hyperbox
- enter it
- place either Energy Acceptor or ME controller
- power it with a flux point
- exit the hyperbox
- break the hyperbox
- Server crash

**Comment by Commoble** [comment]
Does aecapfix fix it?

https://www.curseforge.com/minecraft/mc-mods/aecapfix

**Comment by Satherov** [comment]
It does not

Crash log: https://gist.github.com/Satherov/867e11674348dac6f7f7f41f493707f1

This was done in the ATM9 TTS modpack, but works just as well with just Hyperbox, Fluxnet and Ae2 alone
