### ISSUE TITLE
Mobs Not Spawning

### ISSUE THREAD

**Issue by rannday** [Commoble/hyperbox#31]
I setup a mob farm with Mob Grinding Utils' Dreadful Dirt. No mobs are spawning. 

I have night vision via EveryLastingAbilities, which is why it all seems lit up, but I disabled it then re-entered the Hyperbox, and it seemed plenty dark.

ATM9 To the Sky - 1.1.1

Hyperbox-1.20.1-4.0.2.0

![2024-08-19_11 00 56](https://github.com/user-attachments/assets/cc83ccc1-8dde-4a9d-a988-bca92a1a572f)

**Comment by Commoble** [comment]
The hyperbox biome intentionally has no mob spawn entries
