### ISSUE TITLE
[Question] When are you gonna update this mod to 1.21.0/.1?

### ISSUE THREAD

**Issue by Dinocraft1515YT** [Commoble/hyperbox#35]
When are you gonna update this mod to 1.21.0/.1?
Is there any issue with the develop?

I'm asking because I have a server with this mod in the modpack and I want to know if it will be released soon or not. Just to know if I must put it on a chest in a place that wont be loaded without commands.

**Comment by Commoble** [comment]
Mod is already on 1.21 https://www.curseforge.com/minecraft/mc-mods/hyperbox/files/5555553

**Comment by Dinocraft1515YT** [comment]
I isn't on modrinth

**Comment by Commoble** [comment]
Ahh, I stopped uploading mods to modrinth because it's extra work for me when I update mods, but I forgot to remove the link from the readme, thanks for bringing this to my attention
