### ISSUE TITLE
[Request] Allow "Camouflage" of interior walls 

### ISSUE THREAD

**Issue by Grimjahk** [Commoble/hyperbox#43]
Being, or setting up stuff, in a dark/bleak space makes me sad. 

It would be amazing if you added a way to change the interior walls, similar to how you can camouflage elevators:

A "HyperBrush" that would "paint" interior blocks to match the Full-block in the off-hand would be AMAZEBALLS.

Being able to sneak right-click and set a interior pattern for the entirety of the interior would be cool as well.

Frankly, any option to not feel like I'm in a Obsidian Golem's Digestive tract would be appreciated.

**Comment by Commoble** [comment]
It's intentionally creepy

**Comment by Grimjahk** [comment]
How unfortunate. I just like the mod, I like the concept, I just find myself avoiding using it for that exact reason. Therefore I use it less than it deserves. Last three packs I've only put the Wither and my fully automated farm in there. 

I can imagine that I'm not the only one. 

Still. it would be nice to have the option. (for those that do the research/make the effort)
